### ISSUE TITLE
Alternatives missing in result type

### ISSUE THREAD

**Issue by wodka** [deepgram/node-sdk#16]
## What is the current behavior?

there should be alternatives in the result type

## Steps to reproduce

enable alternatives and try to consume them.

## Expected behavior

The result should have typed alternatives

## Please tell us about your environment

- **Operating System/Version:** *
- **Language:** TypeScript
- **Browser:** *

## Other information

Alternatives are referenced in the API https://developers.deepgram.com/api-reference/ but not in the more detailed documentation

**Comment by MichaelJolley** [comment]
Hi @wodka, alternatives should [exist currently](https://github.com/deepgram/node-sdk/blob/57d6e9105a77afb938f12db8e852076e1812f975/src/types/channel.ts#L12) on the individual channel returned in the transcript. Their location on a result would look like:

```js
const response = await deepgram.transcription.preRecorded(fileSource, {
  punctuate: true,
});
const channel0Alternatives= response.results.channels[0].alternatives
```

Am I misunderstanding?

**Comment by wodka** [comment]
no you are completely right - I missed this. Thank you!
