### ISSUE TITLE
deepgramsocket.finish() method closes websocket instead of sending empty binary frame. 

### ISSUE THREAD

**Issue by justinhall756** [deepgram/node-sdk#23]
## What is the current behavior?

The websocket connection is being closed using the standard .close() method and passing a close code to Deepgram. This will result in the termination of the connection which in many cases causes a failure on the receipt of the last frame of data.

## Steps to reproduce

This can be reproduced by using the SDK to transcribe any audio using streaming. You will often see no response when the audio is very short. You will notice that you will not receive the very last is_final=true & speech_final=true because this final result will have been terminated before it was received when the websocket was closed. 

## Expected behavior

The final frame of transcription results should be received and processed by the SDK before the websocket connection is closed. This can be achieved by sending an empty binary frame after the ending of the stream 

## Please tell us about your environment
  
Running standard node script

**Comment by MichaelJolley** [comment]
Thanks for reporting. Should be fixed by #22.
