### ISSUE TITLE
Output of keys list doesn't match docs

### ISSUE THREAD

**Issue by lukeocodes** [deepgram/node-sdk#25]
## What is the current behavior?

https://developers.deepgram.com/sdks-tools/sdks/node-sdk/keys/#list-project-keys-example-request

These docs suggest this output when I list API keys for a project

```js
{
  api_keys: [
    {
      api_key_id: string,
      comment: string,
      created: string,
      scopes: Array<string>
    },
  ];
}
```

but i get this output

```js
{ 
  api_keys: [
    {
      member: {
        member_id: '...',
        email: '...
      },
      api_key: {
        api_key_id: '...',
        comment: '...',
        scopes: [...],
        created: '...'
      }
    },
    ...
  ]
}
```

**Comment by lukeocodes** [comment]
it looks like the typing is correct to the docs, but what is returned doesn't respect the types?

![image](https://user-images.githubusercontent.com/956290/155800225-ed272ddd-173e-4afc-afd3-6fd966b58c12.png)

**Comment by MichaelJolley** [comment]
This is an issue both with the types on the SDK and the SDK docs. They do not match the [API Reference](https://developers.deepgram.com/api-reference/#keys-get-keys)
