### ISSUE TITLE
TypeError: this._apiKey.trim is not a function

### ISSUE THREAD

**Issue by stacksapien** [deepgram/node-sdk#4]
## What is the current behavior?
When we instantiate the deep gram object in nodejs by following the documentation, we get error like this : 

<MY_APP_DIRECTORY>\node_modules\@deepgram\sdk\dist\index.js:23
        if (!this._apiKey || this._apiKey.trim().length === 0) {
                                          ^

TypeError: this._apiKey.trim is not a function
    at Deepgram._validateOptions (<MY_APP_DIRECTORY>\node_modules\@deepgram\sdk\dist\index.js:23:43)
    at new Deepgram (<MY_APP_DIRECTORY>\node_modules\@deepgram\sdk\dist\index.js:13:14)
    at Object.<anonymous> (<MY_APP_DIRECTORY>\services\transcribe\speech-to-text.js:20:18)
    
> What's happening that seems wrong?
We are not able to instantiate the object of Deepgram due to which we can't access the required APIs using SDK.

## Steps to reproduce
- Declare the objects as follow : 
const { Deepgram } = require("@deepgram/sdk");

const deepgram = new Deepgram({
  apiKey: process.env.DEEPGRAM_API_KEY
});

- Now run the nodejs file.

## Please tell us about your environment
OS: Windows 10 Build 19042
NodeJS : v12.18.0

As a workaround, It worked in this way : 

const deepgram = new Deepgram(process.env.DEEPGRAM_API_KEY);

**Comment by MichaelJolley** [comment]
Thanks for reporting @stacksapien! You're right. PR incoming to fix.
